version: '2.3'

networks:
  default:
    external:
      name: net_substra

services:

  substrabacowkin:
    container_name: owkin.substrabac
    hostname: substrabacowkin
    build:
        context: ./
        dockerfile: ./docker/substrabac/Dockerfile
    command: /bin/bash -c "while ! { nc -z postgresql 5432 2>&1; }; do sleep 1; done; python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./substrabac/medias:/usr/src/app/medias
      # /!\ DO NOT MOUNT WITH CURRENT PORT SETUP
      # - ./substrabac/substrapp/conf:/usr/src/app/substrapp/conf
    links:
      - postgresql
      - rabbit
    ports:
      - "8000:8000"
    depends_on:
      - postgresql
      - rabbit
    environment:
      - DATABASE_HOST=postgresql
      - DJANGO_SETTINGS_MODULE=substrabac.settings.dev.owkin
      - PYTHONUNBUFFERED=1

  substrabacchunantes:
    container_name: chunantes.substrabac
    hostname: substrabacchunantes
    build:
        context: ./
        dockerfile: ./docker/substrabac/Dockerfile
    command: /bin/bash -c "while ! { nc -z postgresql 5432 2>&1; }; do sleep 1; done; python3 manage.py runserver 0.0.0.0:8001"
    volumes:
      - ./substrabac/medias:/usr/src/app/medias
      # /!\ DO NOT MOUNT WITH CURRENT PORT SETUP
      # - ./substrabac/substrapp/conf:/usr/src/app/substrapp/conf
    links:
      - postgresql
      - rabbit
    ports:
      - "8001:8001"
    depends_on:
      - postgresql
      - rabbit
    environment:
      - DATABASE_HOST=postgresql
      - DJANGO_SETTINGS_MODULE=substrabac.settings.dev.chunantes
      - PYTHONUNBUFFERED=1

  # Celery worker

  celerybeat:
    container_name: celerybeat
    hostname: celerybeat
    build:
      context: ./
      dockerfile: ./docker/celery/Dockerfile
    command: celery -A substrabac beat -l info -b rabbit
    links:
      - rabbit
    depends_on:
      - rabbit
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=substrabac.settings.dev

  worker_owkin:
    container_name: worker_owkin
    hostname: worker_owkin
    # runtime: nvidia
    build:
      context: ./
      dockerfile: ./docker/celery/Dockerfile
    command: celery -A substrabac worker -l info -n owkin -Q owkin,celery -b rabbit
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./substrabac/medias:/usr/src/app/medias
      # /!\ DO NOT MOUNT WITH CURRENT PORT SETUP
      # - ./substrabac/substrapp/conf:/usr/src/app/substrapp/conf
    links:
      - rabbit
      - substrabacowkin
    depends_on:
      - rabbit
    environment:
      - ORG=owkin
      - PYTHONUNBUFFERED=1
      - DATABASE_HOST=postgresql
      - DJANGO_SETTINGS_MODULE=substrabac.settings.dev.owkin
      - DOCKER_MEDIA_ROOT=${PWD}/substrabac

  worker_chunantes:
    container_name: worker_chunantes
    hostname: worker_chunantes
    # runtime: nvidia
    build:
      context: ./
      dockerfile: ./docker/celery/Dockerfile
    command: celery -A substrabac worker -l info -n chunantes -Q chu-nantes,celery -b rabbit
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./substrabac/medias:/usr/src/app/medias
      # /!\ DO NOT MOUNT WITH CURRENT PORT SETUP
      # - ./substrabac/substrapp/conf:/usr/src/app/substrapp/conf
    links:
      - rabbit
    depends_on:
      - rabbit
      - substrabacchunantes
    environment:
      - ORG=chu-nantes
      - PYTHONUNBUFFERED=1
      - DATABASE_HOST=postgresql
      - DJANGO_SETTINGS_MODULE=substrabac.settings.dev.chunantes
      - DOCKER_MEDIA_ROOT=${PWD}/substrabac


  rabbit:
    container_name: rabbit
    hostname: rabbit
    image: rabbitmq:3
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - HOSTNAME=rabbitmq
      - RABBITMQ_NODENAME=rabbitmq
    ports:
      - "5672:5672"

  postgresql:
    container_name: postgresql
    hostname: postgresql
    build:
      context: ./
      dockerfile: ./docker/postgresql/Dockerfile
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - USER=postgres
      - POSTGRES_PASSWORD=postgrespwd
      - POSTGRES_DB=substrabac

  flower:
    container_name: flower
    image: mher/flower
    ports:
      - "5555:5555"
    depends_on:
      - rabbit
    environment:
      - CELERY_BROKER_URL=amqp://rabbit:5672
