version: '2.3'

networks:
  default:
    external:
      name: net_substra

services:

  substrabacowkin:
    container_name: owkin.substrabac
    hostname: substrabacowkin
    image: substra/substrabac
    command: /bin/bash -c "while ! { nc -z postgresql 5432 2>&1; }; do sleep 1; done; python manage.py migrate --settings=substrabac.settings.dev.owkin; python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - /substra:/substra
      - /substra/data/orgs/owkin/user/msp:/opt/gopath/src/github.com/hyperledger/fabric/peer/msp
    links:
      - postgresql
      - rabbit
    ports:
      - "8000:8000"
    depends_on:
      - postgresql
      - rabbit
    environment:
      - DATABASE_HOST=postgresql
      - DJANGO_SETTINGS_MODULE=substrabac.settings.dev.owkin
      - PYTHONUNBUFFERED=1
      - FABRIC_CFG_PATH=/substra/conf/owkin/peer1/

  substrabacchunantes:
    container_name: chunantes.substrabac
    hostname: substrabacchunantes
    image: substra/substrabac
    command: /bin/bash -c "while ! { nc -z postgresql 5432 2>&1; }; do sleep 1; done; python manage.py migrate --settings=substrabac.settings.dev.chunantes; python3 manage.py runserver 0.0.0.0:8001"
    volumes:
      - /substra:/substra
      - /substra/data/orgs/chu-nantes/user/msp:/opt/gopath/src/github.com/hyperledger/fabric/peer/msp
    links:
      - postgresql
      - rabbit
    ports:
      - "8001:8001"
    depends_on:
      - postgresql
      - rabbit
    environment:
      - DATABASE_HOST=postgresql
      - DJANGO_SETTINGS_MODULE=substrabac.settings.dev.chunantes
      - PYTHONUNBUFFERED=1
      - FABRIC_CFG_PATH=/substra/conf/chu-nantes/peer1/

  # Celery worker

  celerybeat:
    container_name: celerybeat
    hostname: celerybeat
    image: substra/celerybeat
    command: /bin/bash -c "while ! { nc -z rabbit 5672 2>&1; }; do sleep 1; done; celery -A substrabac beat -l info -b rabbit"
    volumes:
      - /substra:/substra
    links:
      - rabbit
    depends_on:
      - rabbit
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=substrabac.settings.dev

  worker_owkin:
    container_name: worker_owkin
    hostname: worker_owkin
    # runtime: nvidia
    image: substra/celeryworker
    command: /bin/bash -c "while ! { nc -z rabbit 5672 2>&1; }; do sleep 1; done; celery -A substrabac worker -l info -n owkin -Q owkin,celery -b rabbit"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /substra:/substra
      - /substra/data/orgs/owkin/user/msp:/opt/gopath/src/github.com/hyperledger/fabric/peer/msp
    links:
      - rabbit
      - substrabacowkin
    depends_on:
      - rabbit
    environment:
      - ORG=owkin
      - PYTHONUNBUFFERED=1
      - DATABASE_HOST=postgresql
      - DJANGO_SETTINGS_MODULE=substrabac.settings.dev.owkin
      - FABRIC_CFG_PATH=/substra/conf/owkin/peer1/

  worker_chunantes:
    container_name: worker_chunantes
    hostname: worker_chunantes
    # runtime: nvidia
    image: substra/celeryworker
    command: /bin/bash -c "while ! { nc -z rabbit 5672 2>&1; }; do sleep 1; done; celery -A substrabac worker -l info -n chunantes -Q chu-nantes,celery -b rabbit"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /substra:/substra
      - /substra/data/orgs/chu-nantes/user/msp:/opt/gopath/src/github.com/hyperledger/fabric/peer/msp
    links:
      - rabbit
    depends_on:
      - rabbit
      - substrabacchunantes
    environment:
      - ORG=chu-nantes
      - PYTHONUNBUFFERED=1
      - DATABASE_HOST=postgresql
      - DJANGO_SETTINGS_MODULE=substrabac.settings.dev.chunantes
      - FABRIC_CFG_PATH=/substra/conf/chu-nantes/peer1/


  rabbit:
    container_name: rabbit
    hostname: rabbit
    image: rabbitmq:3
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - HOSTNAME=rabbitmq
      - RABBITMQ_NODENAME=rabbitmq
#    ports:
#      - "5672:5672"

  postgresql:
    container_name: postgresql
    hostname: postgresql
    image: substra/postgresql
    volumes:
      - /substra/backup/postgres-data:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - USER=postgres
      - POSTGRES_PASSWORD=postgrespwd
      - POSTGRES_DB=substrabac

#  flower:
#    container_name: flower
#    image: mher/flower
#    ports:
#      - "5555:5555"
#    depends_on:
#      - rabbit
#    environment:
#      - CELERY_BROKER_URL=amqp://rabbit:5672
