{{- if .Values.docker.pullImages }}}
{{- if .Values.docker.config }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.docker.config }}
metadata:
  name: {{ template "substra.fullname" . }}-pull-docker-images-creds
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ template "substra.name" . }}-pull-docker-images-creds
    app.kubernetes.io/part-of: {{ template "substra.name" . }}
---
{{- end }}
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "substra.fullname" . }}-pull-docker-images
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ template "substra.name" . }}-pull-docker-images
    app.kubernetes.io/part-of: {{ template "substra.name" . }}
spec:
  selector:
    matchLabels:
      name: {{ template "substra.fullname" . }}-pull-docker-images
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: {{ template "substra.fullname" . }}-pull-docker-images
    spec:
      initContainers:
      - image: docker
        name: init
        resources:
          requests:
            cpu: 0.15
        securityContext:
          privileged: true
        command: ["sh", "-c"]
        args:
          - |
          {{- range .Values.docker.pullImages }}
            docker pull {{ . }}
          {{- end }}
        volumeMounts:
        - name: dockersock
          mountPath: "/var/run/docker.sock"
        {{- if .Values.docker.config }}
        - name: dockerconfig
          mountPath: "/root/.docker"
        {{- end }}
      containers:
      - image: "gcr.io/google-containers/pause:2.0"
        name: pause
      volumes:
      - name: dockersock
        hostPath:
          path: {{ .Values.docker.socket }}
      {{- if .Values.docker.config }}
      - name: dockerconfig
        secret:
          secretName: {{ template "substra.fullname" . }}-pull-docker-images-creds
          items:
          - key: .dockerconfigjson
            path: config.json
      {{- end }}
{{- end }}
