apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "substra.fullname" . }}-server
data:
  conf.json: |
    {
      "name": "{{ .Values.organization.name }}",
      "core_peer_mspconfigpath": "/var/hyperledger/msp",
      "channel_name": "{{ .Values.channel }}",
      "chaincode_name": "{{ .Values.chaincode.name }}",
      "chaincode_version": "{{ .Values.chaincode.version }}",
      "client": {
        "name": "{{ .Values.user.name }}",
        "org": "{{ .Values.organization.name }}",
        "state_store": "/tmp/hfc-cvs",
        "key_path": "/var/hyperledger/msp/keystore/*",
        "cert_path": "/var/hyperledger/msp/signcerts/cert.pem",
        "msp_id": "{{ .Values.peer.mspID }}"
      },
      "peer": {
        "name": "peer",
        "host": "{{ .Values.peer.host }}",
        "port": {
          "internal": {{ .Values.peer.port }},
          "external": {{ .Values.peer.port }}
        },
        "docker_core_dir": "/var/hyperledger/fabric_cfg",
        "tlsCACerts": "/var/hyperledger/ca/cacert.pem",
        "clientKey": "/var/hyperledger/tls/client/pair/tls.key",
        "clientCert": "/var/hyperledger/tls/client/pair/tls.crt",
        "grpcOptions": {
          "grpc.ssl_target_name_override": "{{ .Values.peer.host }}",
          "grpc.max_send_message_length": -1,
          "grpc.max_receive_message_length": -1
        }
      }
    }

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "substra.fullname" . }}-server-uwsgi
data:
  uwsgi.ini: |
    [uwsgi]
    # chdir           = /usr/src/app
    module          = backend.wsgi
    env             = DJANGO_SETTINGS_MODULE=backend.settings.server.{{ .Values.backend.settings }}
    static-map      = /static=/usr/src/app/backend/statics

    master          = true
    processes       = {{ .Values.backend.uwsgiProcesses }}
    threads         = {{ .Values.backend.uwsgiThreads }}
    http            = :{{ .Values.backend.service.port }}
    # socket          = /tmp/substra-backend.sock
    # chmod-socket    = 664

    need-app        = true
    http-timeout    = 300
    socket-timeout  = 300
    harakiri        = 300
