{{- if .Values.privateCa.configMap.data }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.privateCa.configMap.name }}
  labels:
    {{ include "substra.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "substra.name" . }}
data:
  {{ .Values.privateCa.configMap.fileName }}: |
{{ .Values.privateCa.configMap.data | indent 4}}
{{- end }}
