apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "substra.fullname" . }}-celerybeat
  labels:
    {{ include "substra.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ template "substra.name" . }}-celerybeat
spec:
  replicas: {{ .Values.celerybeat.replicaCount }}
  selector:
    matchLabels:
        app.kubernetes.io/name: {{ template "substra.name" . }}-celerybeat
        {{ include "substra.selectorLabels" . | nindent 8}}
  template:
    metadata:
      labels:
        {{ include "substra.labels" . | nindent 8 }}
        app.kubernetes.io/name: {{ template "substra.name" . }}-celerybeat
    spec:
      {{- with $.Values.celerybeat.image.pullSecrets }}
      imagePullSecrets:
      {{- range . }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      containers:
        - name: celerybeat
          image: "{{ .Values.celerybeat.image.repository }}:{{ .Values.celerybeat.image.tag }}"
          {{- if .Values.celerybeat.image.pullPolicy }}
          imagePullPolicy: "{{ .Values.celerybeat.image.pullPolicy }}"
          {{- end }}
          {{- if .Values.securityContext.enabled }}
          securityContext:
            runAsUser: {{ .Values.securityContext.runAsUser }}
            runAsGroup: {{ .Values.securityContext.runAsGroup }}
          {{- end }}
          command: ["/bin/bash"]
          {{- if eq .Values.backend.settings "prod" }}
          args: ["-c", "celery -A backend beat -l debug"]
          {{ else }}
          args: ["-c", "watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- celery -A backend beat -l debug"]
          {{ end }}
          env:
            - name: CELERY_BROKER_URL
              value: "amqp://{{ .Values.rabbitmq.rabbitmq.username }}:{{ .Values.rabbitmq.rabbitmq.password }}@{{ .Release.Name }}-{{ .Values.rabbitmq.host }}:{{ .Values.rabbitmq.port }}//"
            - name: DJANGO_SETTINGS_MODULE
              value: backend.settings.common
            - name: SCHEDULE_TASK_PERIOD
              value: "{{ .Values.celerybeat.taskPeriod }}"
            - name: PYTHONUNBUFFERED
              value: "1"
          resources:
            {{- toYaml .Values.celerybeat.resources | nindent 12 }}
    {{- with .Values.celerybeat.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.celerybeat.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.celerybeat.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
