apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "substra.fullname" . }}-kaniko-cache-warmer
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ template "substra.name" . }}-kaniko-cache-warmer
    app.kubernetes.io/part-of: {{ template "substra.name" . }}
spec:
  template:
    spec:
      # Run the cache warmer on the same node as the worker.
      # This pod and the kaniko pod both use the "docker-cache" PV.
      # To be successfully mounted on both pods, this PV and the 2 pods all need to
      # be scheduled on the same node.
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - {{ template "substra.name" . }}-worker
            topologyKey: kubernetes.io/hostname
      containers:
      - name: kaniko-cache-warmer
        image: gcr.io/kaniko-project/warmer:latest
        args:
        - "--cache-dir=/cache"
        {{- range .Values.prePulledImages }}
        - "--image={{ . }}"
        {{- end }}
        volumeMounts:
        - name: kaniko-cache
          mountPath: /cache
          readOnly: False
      restartPolicy: Never
      volumes:
      - name: kaniko-cache
        persistentVolumeClaim:
          claimName: {{ include "substra.fullname" $ }}-docker-cache
  backoffLimit: 4
