{{- range $index, $value := .Values.pullSecretsInline }}
---
apiVersion: v1
data:
  .dockerconfigjson: {{ $value }}
kind: Secret
metadata:
  name: {{ template "substra.fullname" $ }}-pull-secret-{{ $index }}
  labels:
    {{ include "substra.labels" $ | nindent 4 }}
    app.kubernetes.io/name: {{ template "substra.fullname" $ }}-pull-secret-{{ $index }}
type: kubernetes.io/dockerconfigjson
{{- end }}
