{{- range $index, $value := .Values.pullSecretsInline }}
---
apiVersion: v1
data:
  .dockerconfigjson: {{ $value }}
kind: Secret
metadata:
  name: {{ template "substra.fullname" $ }}-pull-secret-{{ $index }}
  labels:
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
    app.kubernetes.io/name: {{ template "substra.fullname" $ }}-pull-secret-{{ $index }}
    app.kubernetes.io/part-of: {{ template "substra.name" $ }}
type: kubernetes.io/dockerconfigjson
{{- end }}
