{{- range .Values.persistence.volumes }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    {{ include "substra.labels" $ | nindent 4 }}
  name: {{ template "substra.fullname" $ }}-{{ .name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .size | quote }}
  {{- if $.Values.persistence.hostPath }}
  selector:
    matchLabels:
      {{ include "substra.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/name: {{ template "substra.name" $ }}-{{ .name }}
  {{- else if $.Values.persistence.storageClassName }}
  storageClassName: {{ $.Values.persistence.storageClassName }}
  {{- end }}
---
{{- if $.Values.persistence.hostPath }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "substra.fullname" $ }}-{{ .name }}
  labels:
    {{ include "substra.labels" $ | nindent 4 }}
    app.kubernetes.io/name: {{ template "substra.name" $ }}-{{ .name }}
spec:
  storageClassName: ""
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    name: {{ template "substra.fullname" $ }}-{{ .name }}
    namespace: {{ $.Release.Namespace }}
  capacity:
    storage: {{ .size | quote }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ $.Values.persistence.hostPath }}/medias/{{ .name }}
    type: DirectoryOrCreate
{{- end }}
{{- end }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "substra.fullname" $ }}-servermedias
  labels:
  {{ include "substra.labels" $ | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $.Values.persistence.size | quote }}
  {{- if $.Values.persistence.hostPath }}
  selector:
    matchLabels:
      {{ include "substra.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/name: {{ template "substra.name" $ }}-servermedias
  {{- else if $.Values.persistence.storageClassName }}
  storageClassName: {{ $.Values.persistence.storageClassName }}
  {{- end }}
---
{{- if $.Values.persistence.hostPathServerMedias }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "substra.fullname" $ }}-servermedias
  labels:
    {{ include "substra.labels" $ | nindent 4 }}
    app.kubernetes.io/name: {{ template "substra.name" $ }}-servermedias
spec:
  storageClassName: ""
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    name: {{ template "substra.fullname" $ }}-servermedias
    namespace: {{ $.Release.Namespace }}
  capacity:
    storage: {{ $.Values.persistence.size | quote }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ $.Values.persistence.hostPathServerMedias }}/servermedias
    type: DirectoryOrCreate
{{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "substra.fullname" $ }}-docker-cache
  labels:
    {{ include "substra.labels" $ | nindent 4 }}
    app.kubernetes.io/name: {{ template "substra.name" $ }}-docker-cache
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  {{- if $.Values.persistence.hostPath }}
  selector:
    matchLabels:
      {{ include "substra.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/name: {{ template "substra.name" $ }}-docker-cache
  {{- else if $.Values.persistence.storageClassName }}
  storageClassName: {{ $.Values.persistence.storageClassName }}
  {{- end }}
---
{{- if $.Values.persistence.hostPath }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "substra.fullname" $ }}-docker-cache
  labels:
    {{ include "substra.labels" $ | nindent 4 }}
    app.kubernetes.io/name: {{ template "substra.name" $ }}-docker-cache
spec:
  storageClassName: ""
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    name: {{ template "substra.fullname" $ }}-docker-cache
    namespace: {{ .Release.Namespace }}
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.persistence.hostPath }}/cache
    type: DirectoryOrCreate
{{- end }}
